Icinga/icinga-notifications

icinga2.conf

Similar to the mail notifications in Icinga 2 itself[^0], both the service name and the host name should be urlencoded. Otherwise, as some checks in my demo setup has shown me, the generated URL are invalid.
- Before: …/icingaweb2/icingadb/service?name=random fortune&host.name=foo
- Afterwards: …/icingaweb2/icingadb/service?name=random%20fortune&host.name=foo
Due to limitations of the Icinga 2 language and its libraries, no generic conversation of a char/rune to its char point value was possible. For this reason a (limited) lookup table based on RFC 3986 was chosen. This works until someone starts using Unicode for their names.
[^0]: https://github.com/Icinga/icinga2/blob/v2.14.0/etc/icinga2/scripts/mail-service-notification.sh#L165

icinga2.conf: urlencode service and host names

---

.github/workflows/docker.yml
.github/workflows/go.yml

GitHub branch protection rules can specify that checks are required to succeed, however those are matched by the job name and it's not possible to distinguish by the workflow name. This commit makes the job use distinct names so both can be required individually.

GitHub Actions: remove duplicate job names

---

.github/workflows/go.yml
internal/incident/incident.go
internal/listener/listener.go
internal/object/object.go

Implement the well known meta linter golangci-lint in the CI to check for common errors, also in Pull Requests.
This commit also fixes existing issues raised by golangci-lint: simplifications, cleaning up an unused private struct field, and setting an http.Server's timeouts, which are indefinite by default.

golangci-lint: add as a CI and fix raised concerns

---

cmd/icinga-notifications-daemon/main.go
internal/config/runtime.go
internal/listener/listener.go

This PR works on the initial signal-based context changes from #112. During testing I found my Icinga Notifications container always being stuck when being shut downed until it got SIGKILLed. Thus, next to the introduction of the signal context, a context bug in the `RuntimeConfig` was fixed and a simple context wrapper was added to the `Listener`.
- __listener: context for Listener.Run__
Allow gracefully stopping the internal web server when the parent context is closed.
- __runtime: fix RuntimeConfig.PeriodicUpdates context__
The break only broke out of the select, but continued to for loop.
- __icinga-notifications-daemon: handle SIGINT/SIGTERM__
Switch to a signal based context which is being canceled for SIGINT and SIGTERM. This change was extracted from the ongoing PR #112.

Shutdown Context and Fixes

---

cmd/channel/email/main.go
cmd/channel/rocketchat/main.go
cmd/icinga-notifications-daemon/main.go
internal/channel/channel.go
internal/channel/plugin.go
internal/config/channel.go
internal/daemon/config.go
internal/incident/incident.go
internal/incident/incidents.go
internal/listener/listener.go
pkg/plugin/plugin.go
pkg/rpc/rpc.go
schema/pgsql/schema.sql
schema/pgsql/upgrades/018.sql

resolves https://github.com/Icinga/icinga-notifications/issues/107

Introduce plugin table

---

.github/workflows/go.yml

`only-new-issues` seems to hide some issues in PRs even if they are introduced there.  For example, removing all usages of a struct field without touching the field itself is not detected. This can result in CI failures after merging, see #108 and 6f4b437eaa2f6f42ec56f9cfdd715ace071be04d for example.

golangci-lint: disable only-new-issues

---

cmd/icinga-notifications-daemon/main.go
go.mod
internal/event/event.go
internal/filter/contracts.go
internal/filter/parser.go
internal/filter/parser_test.go
internal/filter/types.go
internal/incident/incident.go
internal/incident/incidents.go
internal/object/db_types.go
internal/rule/condition.go
internal/utils/utils.go

Trigger time based escalations

---

.github/workflows/compliance.yml

By utilizing the neat go-licenses[^0] tool, scanning the cached Go dependencies against an allow list of licenses, which is currently leaned from Icinga DB, works quite like a charm.
This, however, only includes Go code and produces warnings for (transitive) included Go Assembly code[^1]. If we are planning to include other non-Go artefacts in the future, those also might need to be identified - REUSE[^2] might help there.
Closes #139.
For an example, take a look at:
- f944c7a751efaebfea155f2b7d401ec5de91d630, which was a successfully run or
- e04222074127af44567da8aba2e168bb7eb8b0ba, where `MPL-2.0` was missing in the allowed licenses, resulting in an adequate error of:
> Not allowed license MPL-2.0 found for library github.com/go-sql-driver/mysql 
[^0]: …

GitHub Actions: Check Go Dependency Licenses

---

internal/incident/incident.go

The early return from `ProcessEvent()` for acknowledgements meant that the commit of the database transaction later in the function would never happen. This was introduced in 4044b188a9f9423be532d11fc0c70b313fc0ca39 which moved the transaction handling into `ProcessEvent()`

Commit transaction for acknowledgements

---

internal/incident/incident.go

Unlike in Incident.ProcessEvent, Incident.RetriggerEscalations does not call Incident.AddEvent on the freshly synchronized Event. By adding this call, an entry to the incident_event table linking Event and Incident will be created.
Closes #151.

Incident.RetriggerEscalations: incident_event entry

---

cmd/channel/webhook/main.go
pkg/plugin/plugin.go

This PR contains two changes:
* plugin: Document ConfigOption's Help field
* Introduce Webhook Channel
In its initial form, the webhook channel can be used to send notifications against a HTTP/HTTPS web server with a dynamic configurable URL and request body message.
This addresses #144 where @julianbrost [suggested to implement a web hook channel](https://github.com/Icinga/icinga-notifications/pull/144#issuecomment-1877245251).
I have tested this channel locally against <https://github.com/mendhak/docker-http-https-echo> for debugging. Next, I am going to rework #144 to use this channel instead of the file-like channel.

Webhook Channel

---

internal/incident/db_types.go
internal/incident/incident.go
internal/incident/sync.go
schema/pgsql/schema.sql
schema/pgsql/upgrades/023.sql

Next to the schema change, the field and its usage was removed from the Go code. This affects continuous changes to signatures.
refs #163.

Drop incident_history.caused_by_incident_history_id

---

.github/workflows/compliance.yml
.github/workflows/tests_with_database.yml
internal/incident/db_types.go
internal/incident/incident.go
internal/incident/incidents.go
internal/incident/incidents_test.go
internal/incident/sync.go
internal/object/db_types.go
internal/object/object.go
internal/testutils/testutils.go
internal/utils/utils.go

Load active incidents gracefully

---

internal/utils/utils.go
internal/utils/utils_test.go
pkg/plugin/plugin.go

The "Tags" and "Extra Tags" printed in the `plugin.FormatMessage` were directly read from their map, thus having no order. This resulted in the same `NotificationRequest` being represented by different messages due to the unordered map.
This change was the result of investigating Go's new [rangefunc experiment](https://go.dev/wiki/RangefuncExperiment). The utilization of this novel language feature - which can also be indirectly used in the absence of `GOEXPERIMENT=rangefunc` - ensures that the map is traversed in key order.
Closes #177.

utils.IterateOrderedMap for plugin.FormatMessage

---

internal/config/rule.go
internal/event/event.go
internal/icinga2/launcher.go
internal/incident/db_types.go
internal/incident/incident.go
internal/incident/incidents.go
internal/incident/sync.go
internal/recipient/recipient.go
internal/rule/escalation.go
internal/rule/rule.go

This PR proposes the following improvements in preparation for #188.
- 9502b20958f6cbd085952a41e8c05b771096ebda decouples `contactChannels` from the `incident` package, since we're going to use this recipient channels map elsewhere outside the `incident` package in the future and it seems reasonable to me to move it here to the `rule` package.
- d238b0bf33cf0781a2965745f27ccc88fa20d6a4 implements [`zapcore.ObjectMarshaler`](https://pkg.go.dev/go.uber.org/zap/zapcore#ObjectMarshaler) for the `rule.Escalation` and `recipient.Key` types and allows us to use `zap.Inline(escalation)` or `zap.Object("escalation", escalation)`wherever more logging context is needed without having to add all the individual fields ourselves each time.
- ce8732e7e5de9739a11621293da9e743e1e43233 moves the …

Code enhancements for future use

---

schema/pgsql/schema.sql
schema/pgsql/upgrades/025.sql

This feature introduces a new session table which is needed by the `icinga-notifications-web` project.
It stores the current authenticated sessions into the table which allows the background daemon (php-based) to validate a connection and its corresponding browser to an authenticated session.
Read #118 for more information about this addition.

Introduce table for session management

---

schema/pgsql/schema.sql

Schema: fix typo in comment

---

internal/icinga2/api_responses.go
internal/icinga2/api_responses_test.go
internal/icinga2/client_api.go
internal/icinga2/client_api_test.go

The Icinga 2 Event Stream connection did not validate the HTTP status code returned by the server. Consequently, HTTP errors were not identified and their error messages were incorrectly interpreted as valid messages. This occurred in two places: firstly, with regard to the HTTP status code, and secondly, in relation to the error field, which may be present within a JSON struct.
This modification introduces a brief HTTP status validation method that adheres to the specifications outlined in the Icinga 2 API documentation and advanced error checks in UnmarshalEventStreamResponse.

icinga2: Check errors in HTTP status and JSON

---

cmd/icinga-notifications-daemon/main.go
go.mod
go.sum

The default Icinga Notifications systemd service is going to have `Type=notify` in its unit file, so systemd expects us to send this message when the process becomes ready.

Send systemd `READY=1` status message

---

internal/config/schedule.go
internal/config/timeperiod.go
internal/config/verify.go
internal/incident/incident.go
internal/listener/listener.go
internal/recipient/contact.go
internal/recipient/group.go
internal/recipient/recipient.go
internal/recipient/rotations.go
internal/recipient/rotations_test.go
internal/recipient/schedule.go
internal/timeperiod/timeperiod.go
internal/timeperiod/timeperiod_test.go
schema/pgsql/schema.sql
schema/pgsql/upgrades/026.sql

This is a fundamental and incompatible change to how schedules are defined. Now, a schedule consists of a list of rotations that's ordered by priority. Each rotation contains multiple members where each is either a contact or a contact group. Each member is linked to some timeperiod entries which defines when this member is active in the rotation.
This PR already includes code for a feature that was planned but is not yet possible using the web interface at the moment: multiple versions of the same rotation where the handoff time defines when a given version becomes active.
With this change, for the time being, the TimePeriod type itself fulfills no real purpose and the timeperiod entries are directly loaded as part of the schedule, bypassing the timeperiod loading code. However, there …

Change schedule configuration to support new rotations

---

internal/config/runtime.go
schema/pgsql/schema.sql
schema/pgsql/upgrades/027.sql

To allow case-insensitive matches when filtering by these columns.
cc @nilmerg

schema: Require & use `citext` extension

---

schema/pgsql/schema.sql
schema/pgsql/upgrades/029.sql

This PR modifies the `browser_session` table to reflect new changes to the data structure.
- The primary key no longer depends on the `username` or `user_agent`, as the session storage hook takes care of zombie entries before inserting new session data.
- Added the additional descending order to the existing `authenticated_at` index.
- Fixed index naming convention.
- A new combined index has been added, which speeds up lookups that use both `username` and `user_agent` conditions.
- The default expression for `authenticated_at` got removed, as the timestamp now gets supplied by the PHP daemon itself.
Fixes https://github.com/Icinga/icinga-notifications-web/issues/194
Fixes https://github.com/Icinga/icinga-notifications-web/issues/195

Refactor `browser_session` table

---

internal/event/event.go
internal/incident/incident.go
internal/incident/incidents.go
schema/pgsql/schema.sql
schema/pgsql/upgrades/030.sql

The "internal" event type was used both for scheduled reevaluations and for initial reevaluations during startup. This type is currently being used at two different points for two distinct topics: scheduled reevaluations and initial reevaluations during startup.
This event type was now split into "reevaluation-scheduled" and "reevaluation-startup" to distinct those types.
To ensure database-level stability, the column type was changed from text to a custom enum.
Closes #162.

Distinct "internal" Event Types

---

doc/01-About.md

First, relative links outside the `doc` directory are possible and work. However, the main page can be accessed via `…/` or `…/doc/01-About.md`. While a relative link works for the second, it breaks for the first.
For the docs, this link now points to the LICENSE file on GitHub.
Reported-by: Noé Costa <https://github.com/Icinga/icinga-notifications/pull/210#issuecomment-2211076354>

doc/01-About.md: Remove relative link outside doc

---

cmd/channels/email/main.go
cmd/channels/email/main_test.go
cmd/channels/rocketchat/main.go
cmd/channels/webhook/main.go
pkg/plugin/plugin.go

In a nutshell, the newly introduced plugin.PopulateDefaults function
populates all fields of a Plugin-implementing struct with those fields
from Info.ConfigAttributes where ConfigOption.Default is set. Thus, a
single function call before parsing the user-submitted configuration
within the Plugin.SetConfig method sets default values.
As a result of the discussion between the Go and the Web team,
summarized in #205, Web does not store key-value pairs to be omitted.
Prior, an already JSON-encoded version of the ConfigOption slice was
present in plugin.Info. Thus, this data wasn't easily available anymore.
As the new code now needs to access this field, it was changed and a
custom sql driver.Valuer was implemented for a slice type.
While working on this, all ConfigOptions were put in the same …

Channel default value by changing default logic

---

internal/icinga2/api_responses.go
internal/icinga2/client_api.go

This commit implements the `zapcore.ObjectMarshaler` interface for all API / event stream response result types that we currently sprintf the entire Object with `#%v` and allows us to lazily encode all necessary fields without bloating the debug logs with useless information.
**Example output:**
```bash
2024-06-14T16:10:47.521+0200	DEBUG	icinga2	Skipping SOFT event	{"source-id": 1, "name": "passive", "host": "docker-master", "state": 0, "state_type": 1, "in_downtime": false, "acknowledged": false, "last_state_change": "2024-06-14T15:05:22.434+0200", "groups": [], "check_result": {"exit_status": 0, "state": 0, "output": "This is passive check too"}}
2024-06-14T16:10:47.523+0200	DEBUG	icinga2	Skipping SOFT event	{"source-id": 1, "name": "ping4", "host": "DHCP-server", "state": 0, …
```

icinga2: Enhance debug logging

---

.mailmap
AUTHORS

Generated using:
```sh
git log --format='format:%aN <%aE>' | grep -vFx 'dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>' | sort -u > AUTHORS
```
@Al2Klimov @raviks789 I've made the (non-)abbreviation of your names consistent with the [Icinga DB `AUTHORS` file](https://github.com/Icinga/icingadb/blob/main/AUTHORS), please let me know if you prefer something different.

Add AUTHORS and .mailmap

---

internal/icinga2/client_api.go

`Event#Sync()` synchronises an event row with the database only if its ID is set to no other value than `0`. Therefore, we must reset the event ID for the acknowledgement set event generated in the catch-up phase before resending it.

icinga2: Reset `Event#ID` before resending ack set event

---

cmd/channels/email/main.go
cmd/channels/email/main_test.go
cmd/channels/rocketchat/main.go
cmd/channels/webhook/main.go

channels: Mark Required ConfigOptions
Each plugin.ConfigOption was revisited and potentially being marked as
Required, which was missing at some. Furthermore, the order of the
fields was changed to match the struct field order of ConfigOption.
channels: Reorder methods according to plugin.Plugin
The plugin.Plugin interface specifies the three methods required for the
channel plugin RPC API in their logical order. Considering that these
channels are the blueprint for external channel development, the order
of implementing channel plugins was changed to correspond to the
interface.
For all files, the main function has been moved to the top.
In addition, the Email.Send method received a documentation string
indicating that it implements the enmime.Sender interface, as it is not
directly …

Channels: Rework default ConfigOptions and reorder methods

---

.github/workflows/tests_with_database.yml
doc/02-Installation.md
internal/channel/plugin.go
internal/event/event.go
schema/mysql/schema.sql
schema/pgsql/schema.sql
schema/pgsql/upgrades/034.sql

Port schema to MySQL 5.7 / MariaDB 10.2

---

internal/icinga2/api_responses.go
internal/icinga2/client.go
internal/icinga2/client_api.go
internal/icinga2/util.go

The Icinga 2 Checkable `flapping` runtime attribute is always updated even when flapping detection is disabled and leads to false positives, causing Icinga Notifications to falsely suppress an incident. To prevent this, this PR additionally checks for the `enable_flapping` attribute of a checkable and globally for the `IcingaApplication` type.
And YES, I can safely use `app` as a json key because of this.
```bash
[2024-07-08 11:20:18 +0200] critical/config: Error: Validation failed for object 'my-app' of type 'IcingaApplication'; Attribute 'name': Application object must be named 'app'.
Location: in /Users/yhabteab/Workspace/icinga2/prefix/etc/icinga2/features-enabled/app.conf: 1:0-1:32
/Users/yhabteab/Workspace/icinga2/prefix/etc/icinga2/features-enabled/app.conf(1): object …
```

Ignore flapping state if flapping detection isn't enabled

---

Dockerfile

Building the container image started showing the following two warning for me recently which are addressed by this commit:
```
2 warnings found (use --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 3)
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 4)
```

Fix warnings during docker build

---

internal/icinga2/client_api.go

When creating an acknowledgement in Icinga Web, a comment is also added. It is possible, however, to later delete the comment while keeping the object acknowledged.
Deleting acknowledgement comments was not an expected behavior, requiring the presence of an associated comment for each acknowledgement. Otherwise, the catch-up-phase would not succeed.
Unfortunately, there is no way to later add an author to an acknowledgement unless a matching comment exists. Thus, the catch-up-phase will now generalize this acknowledgement into a common muted event, missing the details available in the comment.
Closes #245.

icinga2: Common Muted Event for Acknowledgements w/o Comments during Catch-Up

---

schema/mysql/schema.sql
schema/mysql/upgrades/035.sql
schema/pgsql/schema.sql
schema/pgsql/upgrades/035.sql

* This isn't necessary anymore due to https://github.com/Icinga/icinga-notifications/pull/203#discussion_r1643021910
* No web changes are necessary
* Fresh and upgraded schema don't differ

Schema: don't limit browser_session.user_agent to 4096 chars

---

config.example.yml
doc/03-Configuration.md

Adds just some basic documents to the configuration options in the `config.example.yml` file and also the missing `api-timeout` docs.

Document `api-timeout` & config options in `config.example.yml`

---

.github/workflows/docker.yml

With this change, the Docker GitHub Action now creates multi-platform Docker images on releases and pushes those to Docker Hub. The changes were both inspired by the Docker defaults and <https://github.com/Icinga/icinga-kubernetes/blob/main/.github/workflows/docker-image.yml>.
Note: I am unable to check if the necessary environment variables are already set in this repository. This needs to be done by somebody with the sufficient privileges first. Furthermore, there is no project on Docker Hub so far, maybe it needs to be created first.

Docker GHA: Upload Docker images on release

---

.github/workflows/docker.yml

By default, BuildKit checks out the git repository but does not include the `.git` directory in the build context. This then prevents `go build` from embedding the commit hash into the binary which we want to include in the `--version` output. This behavior can be changed by setting a build argument and fixes our `--version` output.
This also implies that the use of `actions/checkout` was actually redundant and I've removed it in a separate commit.
The changes to the `Dockerfile` (b7281ce14b56343515ccaf8810c10d700f887328) are intended to demonstrate that this actually fixes the issue. After an initial review, I'd remove that commit, wait for a final approval and then merge it.
fixes #257

Container images: show git commit hash in --version output when built on GitHub Actions

---

CHANGELOG.md
internal/version.go

A quick bug fix release, mainly for an annoying logging bug (#264/#267).

Version 0.1.1

---

.github/workflows/go.yml
.golangci.yml
cmd/channels/rocketchat/main.go
cmd/icinga-notifications/main.go
internal/channel/plugin.go
internal/config/verify.go
internal/icinga2/client.go
internal/listener/listener.go
internal/object/object.go

Within the last months, some of the linters used by golangci-lint started detecting more issues, resulting in reports for Icinga Notifications. Some errors were addressed, others marked as false positives, and a .golangci.yml configuration was created with a list of additional linters selected by trusting my gut.
---
Fixes #289.

golangci-lint: Address issues and config

---

internal/object/objects_test.go

any(1720702049000) is an int which only has 32 bits on 32 bit and overflows at compile time. An int64 doesn't.
This PR repairs our pipelines.
`docker run --rm -itv "$(pwd):/icinga-notifications" -w /icinga-notifications --platform linux/386 golang go test ./...`
https://git.icinga.com/packages/icinga-notifications/-/pipelines/36170
```
internal/object/objects_test.go:26:18: cannot use 1720702049000 (untyped int constant) as int value in map literal (overflows)
ok  	github.com/icinga/icinga-notifications/cmd/channels/email	0.099s
?   	github.com/icinga/icinga-notifications/cmd/channels/rocketchat	[no test files]
?   	github.com/icinga/icinga-notifications/cmd/channels/webhook	[no test files]
?   	github.com/icinga/icinga-notifications/cmd/icinga-notifications	[no test files]
? …
```

Make unit tests compile on 32 bit

---

doc/02-Installation.md

There was a bug report in the Icinga Community Forum[^0] regarding an unknown SQL function when using MariaDB 10.3.39. The function in question was `JSON_OBJECTAGG`, only being used in one place by web[^1].
MariaDB's documentation states that this function was introduced in version 10.5.0[^2], greater than the currently documented infimum. This fixes our docs.
MySQL has introduced this function in version 5.7.22[^3] and its required version was incremented as well.
This function's counterpart in PostgreSQL, `json_object_agg`, is available in the required versions[^4].
[^0]: https://community.icinga.com/t/current-state-of-icinga-notifications-modules/14666
[^1]: https://github.com/Icinga/icinga-notifications-web/blob/ede7734436ddee952f89295932fbc05e0b4af6e7/library/Notifications/Model/Behav …

doc: Bump MySQL/MariaDB version for JSON_OBJECTAGG

---

doc/03-Configuration.md

While working on an issue where the additional logging information provided by zap fields was missing, I realized that our documentation did not indicate how to view them. So a new documentation section has been added explaining how to view the fields when using the `systemd-journald` logging output.
Also removes one trailing space.
This change is an almost identical replica of <https://github.com/Icinga/icingadb/pull/743>.

doc/03-Configuration.md: Logging Fields in Journald
